name = "SequenceTransformations"
uuid = "f3633a66-1685-5754-a02e-de255896c9a5"
version = "0.0.0"

[compat]
SpecialFunctions = "0.8, 0.9"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "SpecialFunctions", "Test"]
